// <auto-generated />
namespace CustomerPoint.Service.MotInspections.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LinkServicesWithResources : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkServicesWithResources));
        
        string IMigrationMetadata.Id
        {
            get { return "201607120958423_LinkServicesWithResources"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
